api-version: 1.18
author: Kilo
description: The core plugin for TheBetterChoice
name: TBCCore
version: 1.0.6.0
main: com.thebetterchoiceminecraft.TBCPlugin
website: https://www.tbcraft.fun
softdepend:
  - AdvancedEnchantments
  - MythicLib
  - MythicMobs
  - MMOCore
  - MMOItems
  - MythicEnchants
  - Spartan
  - SuperAuth
  - Citizens
  - Alchema
depend:
  - TheAPI
commands: []